version: '3'

services:

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    env_file:
      - .env
    networks:
      - network
  
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    env_file:
      - .env
    networks:
      - network
  
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - network

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/tcharpen/data/mysql
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/tcharpen/data/wordpress
      o: bind

networks:
  network:
    driver: bridge
